# Generated by Django 5.0.4 on 2025-01-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appn1', '0002_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
