# Generated by Django 5.0.4 on 2025-01-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appn1', '0003_alter_musician_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table='Musician',
        ),
    ]
