# Generated by Django 5.0.4 on 2025-01-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appn1', '0004_alter_musician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
